name: Create a release in master branch

on:
  push:
    branches: [ master ]

jobs:
  create-release:
    name: Create a release in master branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: 'Get next minor version'
        id: next_minor_version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}

      - name: 'Create new milestone'
        id: create_milestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.next_minor_version.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: get_changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.next_minor_version.outputs.patch }}
          release_name: Release v${{ steps.next_minor_version.outputs.patch }}
          body: |
            ${{ steps.get_changelog.outputs.changelog }}
          draft: false
          prerelease: false